# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e964b0b09b91604061f8fa9b02e9322627cbf7418df1b9c04f05edfcade393e05ed03fb0a121f26ac1fa9d48facf23488eaccc5bd46a13e77e8164204a516b86

test:
  secret_key_base: bb5b0e00e32172b5b6c4026ba85db0c0a8508d5e5c3ad7a60a3a8de4eb4c953e156002ef22866d008f319ab8ff37a74fa1a040ea6b94387d787b5ef9b5a138af

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
